## Register a 'cell magic' to let us save the code in a cell to file and run the python

In [1]:
from IPython.core.magic import register_cell_magic


@register_cell_magic
def write_and_run(line, cell):
    argz = line.split()
    file = argz[-1]
    mode = 'w'
    if len(argz) == 2 and argz[0] == '-a':
        mode = 'a'
    with open(file, mode) as f:
        f.write(cell)
    get_ipython().run_cell(cell)

# import classes from modules

In [2]:
import numpy as np
from LearnedRuleModel import LearnedRuleModel

## Next cell contains your class definition
### The first line saves the python code   to file every time the cell is run

In [95]:
%%write_and_run GreedyRuleInductionModel.py



class GreedyRuleInductionModel(LearnedRuleModel):
    
    def __init__(self,maxRules=10, increments=25):
        # call the init function for the super class
        # and inherit all the other methods
        super().__init__(maxRules=maxRules, increments=increments)


        
    def fit( self,train_X,train_y):
      #  Preprocess (trainingset)  
      # store the set of different labels - don't assume theyare 0,12,2 etc
        self.labels = np.unique(train_y)

        # remember how many features there are describing each trainig case
        self.numFeatures= train_X.shape[1]
        
        # preprocess the data to compute the set of thresholds  to be used in rules
        # there are self.numThresholds of these for each feature
        self.CalculatePossibleThresholds(train_X)
        
        numOperators = 3
        score = 0
#         [self.numFeatures , numOperators , threshold_id , CalculatePossibleThresholds(train_X)]
        # now to learn from the data
        
        ###== YOUR CODE HERE====####
            ## I suggest you copy in the pseudocode from the lecture then code to that
            ## some of the lines in that pseudocode have been covered above
            ## and some are covered in the init() method
            
#        WHILE (currentModel.score<trainingsetSize and numRule < maxRules) DO 
        while score < self.numFeatures and self.numRules < self.maxRules:
#            SET bestchild = emptyModel
                bestchild = self.ruleSet.copy()
                bestchildscore = score
#            FOR newRule in (all_possible_rules) 
                for newRule in train_X:
                    print(newRule)
#                SET newModel = COPY(currentModel)
#                     newModel = bestchild.copy()
# # # #                SET newModel = ADDRULE (newModel, newRule)
#                     newModel = np.add(newModel , newRule)
# # #                SET score = SCORE(newModel)
#                     score = self.Score(newModel, newRule, train_X,train_y)
#                     print(score)
# #                IF (newModel.score > bestChild.score)
#                     if score > bestchildscore:
# # #                   SET bestChild= COPY(newModel)
#                         bestchild = newModel.copy()
# # #             IF (bestChild.score > currentModel.score)
#                     if bestchildscore > score:
# # #                SET currentModel=COPY (bestChild)
#                         self.ruleSet = self.ruleSet.copy()
# #                  #SET numRules += 1
#                         self.numRules ++1 
#         return self.ruleSet
#         print(newModel)
#        RETURN currentModel
        

        
    
    def predict(self, examples):
        ypred = np.zeros(examples.shape[0],-999, dtype=np.uint)
 
   
    
        ###== YOUR CODE HERE====####
            ## I suggest you start by setting everything in ypred to a valid default value
            ## i.e. something from the list self.labels
            
            ## then you will find it useful to look at the score() method in the super class
            ## to see how you can try to match rules from your ruleset  for each  test instance in turn
        
        
        # Loop over each example to make predictions about
#         for example in examples:
           # Loop over each rule in model
#             if example
               # Check if example matches rules conditions (HINT: look at score())
                   # Set this example prediction to prediction of rule

       # Set a default prediction e.g. self.labels[0]
       # For each prediction
           #If prediction is default (-1)
               # Set prediction to first class/label e.g. self.labels[0]

        
        return ypred
    




## load the iris data and split it into train/test
### This is just for development, your code will not be tested on the iris data

In [4]:
from  sklearn.model_selection import train_test_split 

#the iris data
from sklearn.datasets import load_iris
irisX,irisy = load_iris(return_X_y = True)
iris_train_X, iris_test_X, iris_train_y, iris_test_y = train_test_split(irisX,irisy, test_size=0.33, stratify=irisy )

irisLabels=['Setosa','Versicolor','Virginica']

# now create an object of my class and test it!

In [96]:
myClassifier = GreedyRuleInductionModel(maxRules=5)
myClassifier.fit(iris_train_X,iris_train_y)

myClassifier.PrintRuleSet()

predictions = myClassifier.predict(iris_test_X)


[5.3 3.7 1.5 0.2]
[5.7 2.8 4.5 1.3]
[4.6 3.2 1.4 0.2]
[6.4 2.8 5.6 2.1]
[6.4 2.9 4.3 1.3]
[6.9 3.1 5.1 2.3]
[5.5 2.5 4.  1.3]
[5.2 4.1 1.5 0.1]
[4.9 3.1 1.5 0.1]
[5.1 3.8 1.5 0.3]
[5.4 3.4 1.5 0.4]
[6.7 3.1 4.7 1.5]
[5.7 2.6 3.5 1. ]
[6.2 2.8 4.8 1.8]
[4.4 3.  1.3 0.2]
[5.2 3.5 1.5 0.2]
[4.4 3.2 1.3 0.2]
[7.3 2.9 6.3 1.8]
[6.2 2.9 4.3 1.3]
[7.2 3.6 6.1 2.5]
[5.  3.6 1.4 0.2]
[5.4 3.4 1.7 0.2]
[4.8 3.4 1.9 0.2]
[6.7 3.1 5.6 2.4]
[5.6 2.9 3.6 1.3]
[5.  3.4 1.5 0.2]
[5.  3.4 1.6 0.4]
[4.9 3.  1.4 0.2]
[4.8 3.1 1.6 0.2]
[6.  2.2 4.  1. ]
[6.3 2.5 5.  1.9]
[6.7 3.3 5.7 2.1]
[7.2 3.  5.8 1.6]
[4.4 2.9 1.4 0.2]
[6.6 3.  4.4 1.4]
[6.5 2.8 4.6 1.5]
[5.1 2.5 3.  1.1]
[6.3 2.3 4.4 1.3]
[5.7 3.8 1.7 0.3]
[5.  2.3 3.3 1. ]
[5.6 2.5 3.9 1.1]
[6.9 3.1 5.4 2.1]
[5.8 2.6 4.  1.2]
[4.9 2.4 3.3 1. ]
[5.1 3.3 1.7 0.5]
[5.  3.5 1.3 0.3]
[6.4 3.2 4.5 1.5]
[6.  3.4 4.5 1.6]
[6.1 3.  4.9 1.8]
[5.1 3.8 1.9 0.4]
[5.8 2.8 5.1 2.4]
[7.4 2.8 6.1 1.9]
[6.1 2.8 4.7 1.2]
[6.1 2.8 4.  1.3]
[4.8 3.4 1.6 0.2]
[7.7 3.8 6

[4.7 3.2 1.3 0.2]
[5.4 3.9 1.7 0.4]
[5.1 3.5 1.4 0.2]
[5.9 3.2 4.8 1.8]
[7.7 3.  6.1 2.3]
[5.9 3.  5.1 1.8]
[5.3 3.7 1.5 0.2]
[5.7 2.8 4.5 1.3]
[4.6 3.2 1.4 0.2]
[6.4 2.8 5.6 2.1]
[6.4 2.9 4.3 1.3]
[6.9 3.1 5.1 2.3]
[5.5 2.5 4.  1.3]
[5.2 4.1 1.5 0.1]
[4.9 3.1 1.5 0.1]
[5.1 3.8 1.5 0.3]
[5.4 3.4 1.5 0.4]
[6.7 3.1 4.7 1.5]
[5.7 2.6 3.5 1. ]
[6.2 2.8 4.8 1.8]
[4.4 3.  1.3 0.2]
[5.2 3.5 1.5 0.2]
[4.4 3.2 1.3 0.2]
[7.3 2.9 6.3 1.8]
[6.2 2.9 4.3 1.3]
[7.2 3.6 6.1 2.5]
[5.  3.6 1.4 0.2]
[5.4 3.4 1.7 0.2]
[4.8 3.4 1.9 0.2]
[6.7 3.1 5.6 2.4]
[5.6 2.9 3.6 1.3]
[5.  3.4 1.5 0.2]
[5.  3.4 1.6 0.4]
[4.9 3.  1.4 0.2]
[4.8 3.1 1.6 0.2]
[6.  2.2 4.  1. ]
[6.3 2.5 5.  1.9]
[6.7 3.3 5.7 2.1]
[7.2 3.  5.8 1.6]
[4.4 2.9 1.4 0.2]
[6.6 3.  4.4 1.4]
[6.5 2.8 4.6 1.5]
[5.1 2.5 3.  1.1]
[6.3 2.3 4.4 1.3]
[5.7 3.8 1.7 0.3]
[5.  2.3 3.3 1. ]
[5.6 2.5 3.9 1.1]
[6.9 3.1 5.4 2.1]
[5.8 2.6 4.  1.2]
[4.9 2.4 3.3 1. ]
[5.1 3.3 1.7 0.5]
[5.  3.5 1.3 0.3]
[6.4 3.2 4.5 1.5]
[6.  3.4 4.5 1.6]
[6.1 3.  4.9 1.8]
[5.1 3.8 1

[6.5 2.8 4.6 1.5]
[5.1 2.5 3.  1.1]
[6.3 2.3 4.4 1.3]
[5.7 3.8 1.7 0.3]
[5.  2.3 3.3 1. ]
[5.6 2.5 3.9 1.1]
[6.9 3.1 5.4 2.1]
[5.8 2.6 4.  1.2]
[4.9 2.4 3.3 1. ]
[5.1 3.3 1.7 0.5]
[5.  3.5 1.3 0.3]
[6.4 3.2 4.5 1.5]
[6.  3.4 4.5 1.6]
[6.1 3.  4.9 1.8]
[5.1 3.8 1.9 0.4]
[5.8 2.8 5.1 2.4]
[7.4 2.8 6.1 1.9]
[6.1 2.8 4.7 1.2]
[6.1 2.8 4.  1.3]
[4.8 3.4 1.6 0.2]
[7.7 3.8 6.7 2.2]
[6.5 3.2 5.1 2. ]
[6.8 3.2 5.9 2.3]
[4.9 3.1 1.5 0.2]
[5.7 2.5 5.  2. ]
[7.  3.2 4.7 1.4]
[5.2 2.7 3.9 1.4]
[5.5 2.6 4.4 1.2]
[5.4 3.  4.5 1.5]
[5.8 2.7 3.9 1.2]
[6.3 3.3 6.  2.5]
[6.9 3.2 5.7 2.3]
[5.6 3.  4.1 1.3]
[5.4 3.7 1.5 0.2]
[5.6 2.8 4.9 2. ]
[5.7 4.4 1.5 0.4]
[5.  2.  3.5 1. ]
[5.  3.3 1.4 0.2]
[6.5 3.  5.5 1.8]
[6.  3.  4.8 1.8]
[7.1 3.  5.9 2.1]
[6.7 3.  5.2 2.3]
[6.5 3.  5.8 2.2]
[6.8 3.  5.5 2.1]
[5.8 2.7 5.1 1.9]
[5.7 2.9 4.2 1.3]
[5.5 2.4 3.7 1. ]
[5.2 3.4 1.4 0.2]
[4.5 2.3 1.3 0.3]
[4.9 2.5 4.5 1.7]
[6.6 2.9 4.6 1.3]
[5.8 2.7 4.1 1. ]
[5.8 2.7 5.1 1.9]
[6.1 3.  4.6 1.4]
[6.4 3.2 5.3 2.3]
[5.5 2.4 3

[4.6 3.6 1.  0.2]
[5.5 3.5 1.3 0.2]
[4.7 3.2 1.3 0.2]
[5.4 3.9 1.7 0.4]
[5.1 3.5 1.4 0.2]
[5.9 3.2 4.8 1.8]
[7.7 3.  6.1 2.3]
[5.9 3.  5.1 1.8]
[5.3 3.7 1.5 0.2]
[5.7 2.8 4.5 1.3]
[4.6 3.2 1.4 0.2]
[6.4 2.8 5.6 2.1]
[6.4 2.9 4.3 1.3]
[6.9 3.1 5.1 2.3]
[5.5 2.5 4.  1.3]
[5.2 4.1 1.5 0.1]
[4.9 3.1 1.5 0.1]
[5.1 3.8 1.5 0.3]
[5.4 3.4 1.5 0.4]
[6.7 3.1 4.7 1.5]
[5.7 2.6 3.5 1. ]
[6.2 2.8 4.8 1.8]
[4.4 3.  1.3 0.2]
[5.2 3.5 1.5 0.2]
[4.4 3.2 1.3 0.2]
[7.3 2.9 6.3 1.8]
[6.2 2.9 4.3 1.3]
[7.2 3.6 6.1 2.5]
[5.  3.6 1.4 0.2]
[5.4 3.4 1.7 0.2]
[4.8 3.4 1.9 0.2]
[6.7 3.1 5.6 2.4]
[5.6 2.9 3.6 1.3]
[5.  3.4 1.5 0.2]
[5.  3.4 1.6 0.4]
[4.9 3.  1.4 0.2]
[4.8 3.1 1.6 0.2]
[6.  2.2 4.  1. ]
[6.3 2.5 5.  1.9]
[6.7 3.3 5.7 2.1]
[7.2 3.  5.8 1.6]
[4.4 2.9 1.4 0.2]
[6.6 3.  4.4 1.4]
[6.5 2.8 4.6 1.5]
[5.1 2.5 3.  1.1]
[6.3 2.3 4.4 1.3]
[5.7 3.8 1.7 0.3]
[5.  2.3 3.3 1. ]
[5.6 2.5 3.9 1.1]
[6.9 3.1 5.4 2.1]
[5.8 2.6 4.  1.2]
[4.9 2.4 3.3 1. ]
[5.1 3.3 1.7 0.5]
[5.  3.5 1.3 0.3]
[6.4 3.2 4.5 1.5]
[6.  3.4 4

[5.2 3.5 1.5 0.2]
[4.4 3.2 1.3 0.2]
[7.3 2.9 6.3 1.8]
[6.2 2.9 4.3 1.3]
[7.2 3.6 6.1 2.5]
[5.  3.6 1.4 0.2]
[5.4 3.4 1.7 0.2]
[4.8 3.4 1.9 0.2]
[6.7 3.1 5.6 2.4]
[5.6 2.9 3.6 1.3]
[5.  3.4 1.5 0.2]
[5.  3.4 1.6 0.4]
[4.9 3.  1.4 0.2]
[4.8 3.1 1.6 0.2]
[6.  2.2 4.  1. ]
[6.3 2.5 5.  1.9]
[6.7 3.3 5.7 2.1]
[7.2 3.  5.8 1.6]
[4.4 2.9 1.4 0.2]
[6.6 3.  4.4 1.4]
[6.5 2.8 4.6 1.5]
[5.1 2.5 3.  1.1]
[6.3 2.3 4.4 1.3]
[5.7 3.8 1.7 0.3]
[5.  2.3 3.3 1. ]
[5.6 2.5 3.9 1.1]
[6.9 3.1 5.4 2.1]
[5.8 2.6 4.  1.2]
[4.9 2.4 3.3 1. ]
[5.1 3.3 1.7 0.5]
[5.  3.5 1.3 0.3]
[6.4 3.2 4.5 1.5]
[6.  3.4 4.5 1.6]
[6.1 3.  4.9 1.8]
[5.1 3.8 1.9 0.4]
[5.8 2.8 5.1 2.4]
[7.4 2.8 6.1 1.9]
[6.1 2.8 4.7 1.2]
[6.1 2.8 4.  1.3]
[4.8 3.4 1.6 0.2]
[7.7 3.8 6.7 2.2]
[6.5 3.2 5.1 2. ]
[6.8 3.2 5.9 2.3]
[4.9 3.1 1.5 0.2]
[5.7 2.5 5.  2. ]
[7.  3.2 4.7 1.4]
[5.2 2.7 3.9 1.4]
[5.5 2.6 4.4 1.2]
[5.4 3.  4.5 1.5]
[5.8 2.7 3.9 1.2]
[6.3 3.3 6.  2.5]
[6.9 3.2 5.7 2.3]
[5.6 3.  4.1 1.3]
[5.4 3.7 1.5 0.2]
[5.6 2.8 4.9 2. ]
[5.7 4.4 1

[6.3 2.5 5.  1.9]
[6.7 3.3 5.7 2.1]
[7.2 3.  5.8 1.6]
[4.4 2.9 1.4 0.2]
[6.6 3.  4.4 1.4]
[6.5 2.8 4.6 1.5]
[5.1 2.5 3.  1.1]
[6.3 2.3 4.4 1.3]
[5.7 3.8 1.7 0.3]
[5.  2.3 3.3 1. ]
[5.6 2.5 3.9 1.1]
[6.9 3.1 5.4 2.1]
[5.8 2.6 4.  1.2]
[4.9 2.4 3.3 1. ]
[5.1 3.3 1.7 0.5]
[5.  3.5 1.3 0.3]
[6.4 3.2 4.5 1.5]
[6.  3.4 4.5 1.6]
[6.1 3.  4.9 1.8]
[5.1 3.8 1.9 0.4]
[5.8 2.8 5.1 2.4]
[7.4 2.8 6.1 1.9]
[6.1 2.8 4.7 1.2]
[6.1 2.8 4.  1.3]
[4.8 3.4 1.6 0.2]
[7.7 3.8 6.7 2.2]
[6.5 3.2 5.1 2. ]
[6.8 3.2 5.9 2.3]
[4.9 3.1 1.5 0.2]
[5.7 2.5 5.  2. ]
[7.  3.2 4.7 1.4]
[5.2 2.7 3.9 1.4]
[5.5 2.6 4.4 1.2]
[5.4 3.  4.5 1.5]
[5.8 2.7 3.9 1.2]
[6.3 3.3 6.  2.5]
[6.9 3.2 5.7 2.3]
[5.6 3.  4.1 1.3]
[5.4 3.7 1.5 0.2]
[5.6 2.8 4.9 2. ]
[5.7 4.4 1.5 0.4]
[5.  2.  3.5 1. ]
[5.  3.3 1.4 0.2]
[6.5 3.  5.5 1.8]
[6.  3.  4.8 1.8]
[7.1 3.  5.9 2.1]
[6.7 3.  5.2 2.3]
[6.5 3.  5.8 2.2]
[6.8 3.  5.5 2.1]
[5.8 2.7 5.1 1.9]
[5.7 2.9 4.2 1.3]
[5.5 2.4 3.7 1. ]
[5.2 3.4 1.4 0.2]
[4.5 2.3 1.3 0.3]
[4.9 2.5 4.5 1.7]
[6.6 2.9 4

[4.6 3.2 1.4 0.2]
[6.4 2.8 5.6 2.1]
[6.4 2.9 4.3 1.3]
[6.9 3.1 5.1 2.3]
[5.5 2.5 4.  1.3]
[5.2 4.1 1.5 0.1]
[4.9 3.1 1.5 0.1]
[5.1 3.8 1.5 0.3]
[5.4 3.4 1.5 0.4]
[6.7 3.1 4.7 1.5]
[5.7 2.6 3.5 1. ]
[6.2 2.8 4.8 1.8]
[4.4 3.  1.3 0.2]
[5.2 3.5 1.5 0.2]
[4.4 3.2 1.3 0.2]
[7.3 2.9 6.3 1.8]
[6.2 2.9 4.3 1.3]
[7.2 3.6 6.1 2.5]
[5.  3.6 1.4 0.2]
[5.4 3.4 1.7 0.2]
[4.8 3.4 1.9 0.2]
[6.7 3.1 5.6 2.4]
[5.6 2.9 3.6 1.3]
[5.  3.4 1.5 0.2]
[5.  3.4 1.6 0.4]
[4.9 3.  1.4 0.2]
[4.8 3.1 1.6 0.2]
[6.  2.2 4.  1. ]
[6.3 2.5 5.  1.9]
[6.7 3.3 5.7 2.1]
[7.2 3.  5.8 1.6]
[4.4 2.9 1.4 0.2]
[6.6 3.  4.4 1.4]
[6.5 2.8 4.6 1.5]
[5.1 2.5 3.  1.1]
[6.3 2.3 4.4 1.3]
[5.7 3.8 1.7 0.3]
[5.  2.3 3.3 1. ]
[5.6 2.5 3.9 1.1]
[6.9 3.1 5.4 2.1]
[5.8 2.6 4.  1.2]
[4.9 2.4 3.3 1. ]
[5.1 3.3 1.7 0.5]
[5.  3.5 1.3 0.3]
[6.4 3.2 4.5 1.5]
[6.  3.4 4.5 1.6]
[6.1 3.  4.9 1.8]
[5.1 3.8 1.9 0.4]
[5.8 2.8 5.1 2.4]
[7.4 2.8 6.1 1.9]
[6.1 2.8 4.7 1.2]
[6.1 2.8 4.  1.3]
[4.8 3.4 1.6 0.2]
[7.7 3.8 6.7 2.2]
[6.5 3.2 5.1 2. ]
[6.8 3.2 5

[6.7 2.5 5.8 1.8]
[4.6 3.6 1.  0.2]
[5.5 3.5 1.3 0.2]
[4.7 3.2 1.3 0.2]
[5.4 3.9 1.7 0.4]
[5.1 3.5 1.4 0.2]
[5.9 3.2 4.8 1.8]
[7.7 3.  6.1 2.3]
[5.9 3.  5.1 1.8]
[5.3 3.7 1.5 0.2]
[5.7 2.8 4.5 1.3]
[4.6 3.2 1.4 0.2]
[6.4 2.8 5.6 2.1]
[6.4 2.9 4.3 1.3]
[6.9 3.1 5.1 2.3]
[5.5 2.5 4.  1.3]
[5.2 4.1 1.5 0.1]
[4.9 3.1 1.5 0.1]
[5.1 3.8 1.5 0.3]
[5.4 3.4 1.5 0.4]
[6.7 3.1 4.7 1.5]
[5.7 2.6 3.5 1. ]
[6.2 2.8 4.8 1.8]
[4.4 3.  1.3 0.2]
[5.2 3.5 1.5 0.2]
[4.4 3.2 1.3 0.2]
[7.3 2.9 6.3 1.8]
[6.2 2.9 4.3 1.3]
[7.2 3.6 6.1 2.5]
[5.  3.6 1.4 0.2]
[5.4 3.4 1.7 0.2]
[4.8 3.4 1.9 0.2]
[6.7 3.1 5.6 2.4]
[5.6 2.9 3.6 1.3]
[5.  3.4 1.5 0.2]
[5.  3.4 1.6 0.4]
[4.9 3.  1.4 0.2]
[4.8 3.1 1.6 0.2]
[6.  2.2 4.  1. ]
[6.3 2.5 5.  1.9]
[6.7 3.3 5.7 2.1]
[7.2 3.  5.8 1.6]
[4.4 2.9 1.4 0.2]
[6.6 3.  4.4 1.4]
[6.5 2.8 4.6 1.5]
[5.1 2.5 3.  1.1]
[6.3 2.3 4.4 1.3]
[5.7 3.8 1.7 0.3]
[5.  2.3 3.3 1. ]
[5.6 2.5 3.9 1.1]
[6.9 3.1 5.4 2.1]
[5.8 2.6 4.  1.2]
[4.9 2.4 3.3 1. ]
[5.1 3.3 1.7 0.5]
[5.  3.5 1.3 0.3]
[6.4 3.2 4

[7.2 3.  5.8 1.6]
[4.4 2.9 1.4 0.2]
[6.6 3.  4.4 1.4]
[6.5 2.8 4.6 1.5]
[5.1 2.5 3.  1.1]
[6.3 2.3 4.4 1.3]
[5.7 3.8 1.7 0.3]
[5.  2.3 3.3 1. ]
[5.6 2.5 3.9 1.1]
[6.9 3.1 5.4 2.1]
[5.8 2.6 4.  1.2]
[4.9 2.4 3.3 1. ]
[5.1 3.3 1.7 0.5]
[5.  3.5 1.3 0.3]
[6.4 3.2 4.5 1.5]
[6.  3.4 4.5 1.6]
[6.1 3.  4.9 1.8]
[5.1 3.8 1.9 0.4]
[5.8 2.8 5.1 2.4]
[7.4 2.8 6.1 1.9]
[6.1 2.8 4.7 1.2]
[6.1 2.8 4.  1.3]
[4.8 3.4 1.6 0.2]
[7.7 3.8 6.7 2.2]
[6.5 3.2 5.1 2. ]
[6.8 3.2 5.9 2.3]
[4.9 3.1 1.5 0.2]
[5.7 2.5 5.  2. ]
[7.  3.2 4.7 1.4]
[5.2 2.7 3.9 1.4]
[5.5 2.6 4.4 1.2]
[5.4 3.  4.5 1.5]
[5.8 2.7 3.9 1.2]
[6.3 3.3 6.  2.5]
[6.9 3.2 5.7 2.3]
[5.6 3.  4.1 1.3]
[5.4 3.7 1.5 0.2]
[5.6 2.8 4.9 2. ]
[5.7 4.4 1.5 0.4]
[5.  2.  3.5 1. ]
[5.  3.3 1.4 0.2]
[6.5 3.  5.5 1.8]
[6.  3.  4.8 1.8]
[7.1 3.  5.9 2.1]
[6.7 3.  5.2 2.3]
[6.5 3.  5.8 2.2]
[6.8 3.  5.5 2.1]
[5.8 2.7 5.1 1.9]
[5.7 2.9 4.2 1.3]
[5.5 2.4 3.7 1. ]
[5.2 3.4 1.4 0.2]
[4.5 2.3 1.3 0.3]
[4.9 2.5 4.5 1.7]
[6.6 2.9 4.6 1.3]
[5.8 2.7 4.1 1. ]
[5.8 2.7 5

[5.8 2.7 3.9 1.2]
[6.3 3.3 6.  2.5]
[6.9 3.2 5.7 2.3]
[5.6 3.  4.1 1.3]
[5.4 3.7 1.5 0.2]
[5.6 2.8 4.9 2. ]
[5.7 4.4 1.5 0.4]
[5.  2.  3.5 1. ]
[5.  3.3 1.4 0.2]
[6.5 3.  5.5 1.8]
[6.  3.  4.8 1.8]
[7.1 3.  5.9 2.1]
[6.7 3.  5.2 2.3]
[6.5 3.  5.8 2.2]
[6.8 3.  5.5 2.1]
[5.8 2.7 5.1 1.9]
[5.7 2.9 4.2 1.3]
[5.5 2.4 3.7 1. ]
[5.2 3.4 1.4 0.2]
[4.5 2.3 1.3 0.3]
[4.9 2.5 4.5 1.7]
[6.6 2.9 4.6 1.3]
[5.8 2.7 4.1 1. ]
[5.8 2.7 5.1 1.9]
[6.1 3.  4.6 1.4]
[6.4 3.2 5.3 2.3]
[5.5 2.4 3.8 1.1]
[6.7 2.5 5.8 1.8]
[4.6 3.6 1.  0.2]
[5.5 3.5 1.3 0.2]
[4.7 3.2 1.3 0.2]
[5.4 3.9 1.7 0.4]
[5.1 3.5 1.4 0.2]
[5.9 3.2 4.8 1.8]
[7.7 3.  6.1 2.3]
[5.9 3.  5.1 1.8]
[5.3 3.7 1.5 0.2]
[5.7 2.8 4.5 1.3]
[4.6 3.2 1.4 0.2]
[6.4 2.8 5.6 2.1]
[6.4 2.9 4.3 1.3]
[6.9 3.1 5.1 2.3]
[5.5 2.5 4.  1.3]
[5.2 4.1 1.5 0.1]
[4.9 3.1 1.5 0.1]
[5.1 3.8 1.5 0.3]
[5.4 3.4 1.5 0.4]
[6.7 3.1 4.7 1.5]
[5.7 2.6 3.5 1. ]
[6.2 2.8 4.8 1.8]
[4.4 3.  1.3 0.2]
[5.2 3.5 1.5 0.2]
[4.4 3.2 1.3 0.2]
[7.3 2.9 6.3 1.8]
[6.2 2.9 4.3 1.3]
[7.2 3.6 6

[5.4 3.4 1.7 0.2]
[4.8 3.4 1.9 0.2]
[6.7 3.1 5.6 2.4]
[5.6 2.9 3.6 1.3]
[5.  3.4 1.5 0.2]
[5.  3.4 1.6 0.4]
[4.9 3.  1.4 0.2]
[4.8 3.1 1.6 0.2]
[6.  2.2 4.  1. ]
[6.3 2.5 5.  1.9]
[6.7 3.3 5.7 2.1]
[7.2 3.  5.8 1.6]
[4.4 2.9 1.4 0.2]
[6.6 3.  4.4 1.4]
[6.5 2.8 4.6 1.5]
[5.1 2.5 3.  1.1]
[6.3 2.3 4.4 1.3]
[5.7 3.8 1.7 0.3]
[5.  2.3 3.3 1. ]
[5.6 2.5 3.9 1.1]
[6.9 3.1 5.4 2.1]
[5.8 2.6 4.  1.2]
[4.9 2.4 3.3 1. ]
[5.1 3.3 1.7 0.5]
[5.  3.5 1.3 0.3]
[6.4 3.2 4.5 1.5]
[6.  3.4 4.5 1.6]
[6.1 3.  4.9 1.8]
[5.1 3.8 1.9 0.4]
[5.8 2.8 5.1 2.4]
[7.4 2.8 6.1 1.9]
[6.1 2.8 4.7 1.2]
[6.1 2.8 4.  1.3]
[4.8 3.4 1.6 0.2]
[7.7 3.8 6.7 2.2]
[6.5 3.2 5.1 2. ]
[6.8 3.2 5.9 2.3]
[4.9 3.1 1.5 0.2]
[5.7 2.5 5.  2. ]
[7.  3.2 4.7 1.4]
[5.2 2.7 3.9 1.4]
[5.5 2.6 4.4 1.2]
[5.4 3.  4.5 1.5]
[5.8 2.7 3.9 1.2]
[6.3 3.3 6.  2.5]
[6.9 3.2 5.7 2.3]
[5.6 3.  4.1 1.3]
[5.4 3.7 1.5 0.2]
[5.6 2.8 4.9 2. ]
[5.7 4.4 1.5 0.4]
[5.  2.  3.5 1. ]
[5.  3.3 1.4 0.2]
[6.5 3.  5.5 1.8]
[6.  3.  4.8 1.8]
[7.1 3.  5.9 2.1]
[6.7 3.  5

[5.7 2.6 3.5 1. ]
[6.2 2.8 4.8 1.8]
[4.4 3.  1.3 0.2]
[5.2 3.5 1.5 0.2]
[4.4 3.2 1.3 0.2]
[7.3 2.9 6.3 1.8]
[6.2 2.9 4.3 1.3]
[7.2 3.6 6.1 2.5]
[5.  3.6 1.4 0.2]
[5.4 3.4 1.7 0.2]
[4.8 3.4 1.9 0.2]
[6.7 3.1 5.6 2.4]
[5.6 2.9 3.6 1.3]
[5.  3.4 1.5 0.2]
[5.  3.4 1.6 0.4]
[4.9 3.  1.4 0.2]
[4.8 3.1 1.6 0.2]
[6.  2.2 4.  1. ]
[6.3 2.5 5.  1.9]
[6.7 3.3 5.7 2.1]
[7.2 3.  5.8 1.6]
[4.4 2.9 1.4 0.2]
[6.6 3.  4.4 1.4]
[6.5 2.8 4.6 1.5]
[5.1 2.5 3.  1.1]
[6.3 2.3 4.4 1.3]
[5.7 3.8 1.7 0.3]
[5.  2.3 3.3 1. ]
[5.6 2.5 3.9 1.1]
[6.9 3.1 5.4 2.1]
[5.8 2.6 4.  1.2]
[4.9 2.4 3.3 1. ]
[5.1 3.3 1.7 0.5]
[5.  3.5 1.3 0.3]
[6.4 3.2 4.5 1.5]
[6.  3.4 4.5 1.6]
[6.1 3.  4.9 1.8]
[5.1 3.8 1.9 0.4]
[5.8 2.8 5.1 2.4]
[7.4 2.8 6.1 1.9]
[6.1 2.8 4.7 1.2]
[6.1 2.8 4.  1.3]
[4.8 3.4 1.6 0.2]
[7.7 3.8 6.7 2.2]
[6.5 3.2 5.1 2. ]
[6.8 3.2 5.9 2.3]
[4.9 3.1 1.5 0.2]
[5.7 2.5 5.  2. ]
[7.  3.2 4.7 1.4]
[5.2 2.7 3.9 1.4]
[5.5 2.6 4.4 1.2]
[5.4 3.  4.5 1.5]
[5.8 2.7 3.9 1.2]
[6.3 3.3 6.  2.5]
[6.9 3.2 5.7 2.3]
[5.6 3.  4

[4.9 2.5 4.5 1.7]
[6.6 2.9 4.6 1.3]
[5.8 2.7 4.1 1. ]
[5.8 2.7 5.1 1.9]
[6.1 3.  4.6 1.4]
[6.4 3.2 5.3 2.3]
[5.5 2.4 3.8 1.1]
[6.7 2.5 5.8 1.8]
[4.6 3.6 1.  0.2]
[5.5 3.5 1.3 0.2]
[4.7 3.2 1.3 0.2]
[5.4 3.9 1.7 0.4]
[5.1 3.5 1.4 0.2]
[5.9 3.2 4.8 1.8]
[7.7 3.  6.1 2.3]
[5.9 3.  5.1 1.8]
[5.3 3.7 1.5 0.2]
[5.7 2.8 4.5 1.3]
[4.6 3.2 1.4 0.2]
[6.4 2.8 5.6 2.1]
[6.4 2.9 4.3 1.3]
[6.9 3.1 5.1 2.3]
[5.5 2.5 4.  1.3]
[5.2 4.1 1.5 0.1]
[4.9 3.1 1.5 0.1]
[5.1 3.8 1.5 0.3]
[5.4 3.4 1.5 0.4]
[6.7 3.1 4.7 1.5]
[5.7 2.6 3.5 1. ]
[6.2 2.8 4.8 1.8]
[4.4 3.  1.3 0.2]
[5.2 3.5 1.5 0.2]
[4.4 3.2 1.3 0.2]
[7.3 2.9 6.3 1.8]
[6.2 2.9 4.3 1.3]
[7.2 3.6 6.1 2.5]
[5.  3.6 1.4 0.2]
[5.4 3.4 1.7 0.2]
[4.8 3.4 1.9 0.2]
[6.7 3.1 5.6 2.4]
[5.6 2.9 3.6 1.3]
[5.  3.4 1.5 0.2]
[5.  3.4 1.6 0.4]
[4.9 3.  1.4 0.2]
[4.8 3.1 1.6 0.2]
[6.  2.2 4.  1. ]
[6.3 2.5 5.  1.9]
[6.7 3.3 5.7 2.1]
[7.2 3.  5.8 1.6]
[4.4 2.9 1.4 0.2]
[6.6 3.  4.4 1.4]
[6.5 2.8 4.6 1.5]
[5.1 2.5 3.  1.1]
[6.3 2.3 4.4 1.3]
[5.7 3.8 1.7 0.3]
[5.  2.3 3

KeyboardInterrupt: 

### lets look at what it predicted

In [ ]:
print(predictions)

 ### lets print out a confusion matrix

In [7]:
# this bit of code prints a simple confusion matrix showing how the predicted labels correspond to the 'real' ones

irisLabels=['Setosa','Versicolor','Virginica']
confusion = np.zeros((3,3))
for row in range (predictions.shape[0]):
    actual = iris_test_y[row]
    predicted = np.argmax(predictions[row])
    confusion [actual] [predicted] += 1

print( '\nPredicted->   Setosa  Versicolor  Virginica')
print( 'Actual ')
for i in range(3):
    print( '{:<10}       {:2.0f}       {:2.0f}       {:2.0f}'.format(irisLabels[i], confusion[i][0], confusion[i][1],confusion[i][2]))




Predicted->   Setosa  Versicolor  Virginica
Actual 
Setosa           17        0        0
Versicolor       16        0        0
Virginica        17        0        0
